# WARNING : This file is machine generated by run_robot_caliblate_mode.py.
# Edit at your own risk.
import numpy as np
NEUTRAL_ANGLE_DEGREES = np.array(
[[-8.5, -7.5, 2.5, -5.5], [44.5, 44.0, 50.0, 36.5], [-40.0, -59.0, -47.0, -52.5]]
)
